# Cancer🔬 Classification: Inference with ⚡`lightning`

**It is continuation of Training: https://www.kaggle.com/code/jirkaborovec/cancer-subtype-tiles-w-lightning-timm-models**

In [1]:
!ls /kaggle/input/pyvips-python-and-deb-package-gpu
# intall the deb packages
!yes | dpkg -i --force-depends /kaggle/input/pyvips-python-and-deb-package-gpu/linux_packages/archives/*.deb
# install the python wrapper
!pip install pyvips -f /kaggle/input/pyvips-python-and-deb-package-gpu/python_packages/ --no-index

linux_packages	python_packages
Selecting previously unselected package apparmor.
(Reading database ... 113818 files and directories currently installed.)
Preparing to unpack .../apparmor_3.0.4-2ubuntu2.2_amd64.deb ...
Unpacking apparmor (3.0.4-2ubuntu2.2) ...
Selecting previously unselected package autoconf.
Preparing to unpack .../autoconf_2.71-2_all.deb ...
Unpacking autoconf (2.71-2) ...
Selecting previously unselected package automake.
Preparing to unpack .../automake_13a1.16.5-1.3_all.deb ...
Unpacking automake (1:1.16.5-1.3) ...
Selecting previously unselected package autotools-dev.
Preparing to unpack .../autotools-dev_20220109.1_all.deb ...
Unpacking autotools-dev (20220109.1) ...
Selecting previously unselected package bzip2-doc.
Preparing to unpack .../bzip2-doc_1.0.8-5build1_all.deb ...
Unpacking bzip2-doc (1.0.8-5build1) ...
Selecting previously unselected package file.
Preparing to unpack .../file_13a5.41-3ubuntu0.1_amd64.deb ...
Unpacking file (1:5.41-3ubuntu0.1) ...
Selecting previously unselected package firefox.
dpkg: regarding .../firefox_13a1snap1-0ubuntu2_amd64.deb containing firefox, pre-dependency problem:
 firefox pre-depends on snapd
  snapd is not installed.

dpkg: warning: ignoring pre-dependency problem!
Preparing to unpack .../firefox_13a1snap1-0ubuntu2_amd64.deb ...
=> Installing the firefox snap
==> Checking connectivity with the snap store
===> System doesn't have a working snapd, skipping
Unpacking firefox (1:1snap1-0ubuntu2) ...
Selecting previously unselected package fonts-droid-fallback.
Preparing to unpack .../fonts-droid-fallback_13a6.0.1r16-1.1build1_all.deb ...
Unpacking fonts-droid-fallback (1:6.0.1r16-1.1build1) ...
Selecting previously unselected package fonts-noto-mono.
Preparing to unpack .../fonts-noto-mono_20201225-1build1_all.deb ...
Unpacking fonts-noto-mono (20201225-1build1) ...
Selecting previously unselected package fonts-urw-base35.
Preparing to unpack .../fonts-urw-base35_20200910-1_all.deb ...
Unpacking fonts-urw-base35 (20200910-1) ...
Selecting previously unselected package gettext-base.
Preparing to unpack .../gettext-base_0.21-4ubuntu4_amd64.deb ...
Unpacking gettext-base (0.21-4ubuntu4) ...
Selecting previously unselected package gettext.
Preparing to unpack .../gettext_0.21-4ubuntu4_amd64.deb ...
Unpacking gettext (0.21-4ubuntu4) ...
Selecting previously unselected package ghostscript.
Preparing to unpack .../ghostscript_9.55.0dfsg1-0ubuntu5.5_amd64.deb ...
Unpacking ghostscript (9.55.0~dfsg1-0ubuntu5.5) ...
Selecting previously unselected package gir1.2-freedesktop:amd64.
Preparing to unpack .../gir1.2-freedesktop_1.72.0-1_amd64.deb ...
Unpacking gir1.2-freedesktop:amd64 (1.72.0-1) ...
Selecting previously unselected package gir1.2-gdkpixbuf-2.0:amd64.
Preparing to unpack .../gir1.2-gdkpixbuf-2.0_2.42.8dfsg-1ubuntu0.2_amd64.deb ...
Unpacking gir1.2-gdkpixbuf-2.0:amd64 (2.42.8+dfsg-1ubuntu0.2) ...
Selecting previously unselected package gir1.2-gsf-1:amd64.
Preparing to unpack .../gir1.2-gsf-1_1.14.47-1build2_amd64.deb ...
Unpacking gir1.2-gsf-1:amd64 (1.14.47-1build2) ...
Selecting previously unselected package gir1.2-harfbuzz-0.0:amd64.
Preparing to unpack .../gir1.2-harfbuzz-0.0_2.7.4-1ubuntu3.1_amd64.deb ...
Unpacking gir1.2-harfbuzz-0.0:amd64 (2.7.4-1ubuntu3.1) ...
Selecting previously unselected package gir1.2-pango-1.0:amd64.
Preparing to unpack .../gir1.2-pango-1.0_1.50.6ds-2ubuntu1_amd64.deb ...
Unpacking gir1.2-pango-1.0:amd64 (1.50.6+ds-2ubuntu1) ...
Selecting previously unselected package gir1.2-poppler-0.18:amd64.
Preparing to unpack .../gir1.2-poppler-0.18_22.02.0-2ubuntu0.2_amd64.deb ...
Unpacking gir1.2-poppler-0.18:amd64 (22.02.0-2ubuntu0.2) ...
Selecting previously unselected package gir1.2-rsvg-2.0:amd64.
Preparing to unpack .../gir1.2-rsvg-2.0_2.52.5dfsg-3ubuntu0.2_amd64.deb ...
Unpacking gir1.2-rsvg-2.0:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Selecting previously unselected package gir1.2-vips-8.0.
Preparing to unpack .../gir1.2-vips-8.0_8.12.1-1build1_amd64.deb ...
Unpacking gir1.2-vips-8.0 (8.12.1-1build1) ...
Selecting previously unselected package gsfonts.
Preparing to unpack .../gsfonts_13a8.11urwcyr1.0.7pre44-4.5_all.deb ...
Unpacking gsfonts (1:8.11+urwcyr1.0.7~pre44-4.5) ...
Selecting previously unselected package icu-devtools.
Preparing to unpack .../icu-devtools_70.1-2_amd64.deb ...
Unpacking icu-devtools (70.1-2) ...
Selecting previously unselected package imagemagick-6-common.
Preparing to unpack .../imagemagick-6-common_83a6.9.11.60dfsg-1.3ubuntu0.22.04.3_all.deb ...
Unpacking imagemagick-6-common (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3) ...
Selecting previously unselected package libaom-dev:amd64.
Preparing to unpack .../libaom-dev_3.3.0-1_amd64.deb ...
Unpacking libaom-dev:amd64 (3.3.0-1) ...
Selecting previously unselected package libblkid-dev:amd64.
Preparing to unpack .../libblkid-dev_2.37.2-4ubuntu3_amd64.deb ...
Unpacking libblkid-dev:amd64 (2.37.2-4ubuntu3) ...
Selecting previously unselected package libbz2-dev:amd64.
Preparing to unpack .../libbz2-dev_1.0.8-5build1_amd64.deb ...
Unpacking libbz2-dev:amd64 (1.0.8-5build1) ...
Selecting previously unselected package libcairo-script-interpreter2:amd64.
Preparing to unpack .../libcairo-script-interpreter2_1.16.0-5ubuntu2_amd64.deb ...
Unpacking libcairo-script-interpreter2:amd64 (1.16.0-5ubuntu2) ...
Selecting previously unselected package libcairo2-dev:amd64.
Preparing to unpack .../libcairo2-dev_1.16.0-5ubuntu2_amd64.deb ...
Unpacking libcairo2-dev:amd64 (1.16.0-5ubuntu2) ...
Selecting previously unselected package libcfitsio-dev:amd64.
Preparing to unpack .../libcfitsio-dev_4.0.0-1_amd64.deb ...
Unpacking libcfitsio-dev:amd64 (4.0.0-1) ...
Selecting previously unselected package libcfitsio-doc.
Preparing to unpack .../libcfitsio-doc_4.0.0-1_all.deb ...
Unpacking libcfitsio-doc (4.0.0-1) ...
Selecting previously unselected package libcfitsio9:amd64.
Preparing to unpack .../libcfitsio9_4.0.0-1_amd64.deb ...
Unpacking libcfitsio9:amd64 (4.0.0-1) ...
Selecting previously unselected package libcgif-dev.
Preparing to unpack .../libcgif-dev_0.2.0-1_amd64.deb ...
Unpacking libcgif-dev (0.2.0-1) ...
Selecting previously unselected package libcgif0.
Preparing to unpack .../libcgif0_0.2.0-1_amd64.deb ...
Unpacking libcgif0 (0.2.0-1) ...
Selecting previously unselected package libdatrie-dev:amd64.
Preparing to unpack .../libdatrie-dev_0.2.13-2_amd64.deb ...
Unpacking libdatrie-dev:amd64 (0.2.13-2) ...
Selecting previously unselected package libdav1d-dev:amd64.
Preparing to unpack .../libdav1d-dev_0.9.2-1_amd64.deb ...
Unpacking libdav1d-dev:amd64 (0.9.2-1) ...
Selecting previously unselected package libde265-0:amd64.
Preparing to unpack .../libde265-0_1.0.8-1_amd64.deb ...
Unpacking libde265-0:amd64 (1.0.8-1) ...
Selecting previously unselected package libde265-dev:amd64.
Preparing to unpack .../libde265-dev_1.0.8-1_amd64.deb ...
Unpacking libde265-dev:amd64 (1.0.8-1) ...
Selecting previously unselected package libdeflate-dev:amd64.
Preparing to unpack .../libdeflate-dev_1.10-2_amd64.deb ...
Unpacking libdeflate-dev:amd64 (1.10-2) ...
Selecting previously unselected package libdjvulibre-dev:amd64.
Preparing to unpack .../libdjvulibre-dev_3.5.28-2build2_amd64.deb ...
Unpacking libdjvulibre-dev:amd64 (3.5.28-2build2) ...
Selecting previously unselected package libdjvulibre-text.
Preparing to unpack .../libdjvulibre-text_3.5.28-2build2_all.deb ...
Unpacking libdjvulibre-text (3.5.28-2build2) ...
Selecting previously unselected package libdjvulibre21:amd64.
Preparing to unpack .../libdjvulibre21_3.5.28-2build2_amd64.deb ...
Unpacking libdjvulibre21:amd64 (3.5.28-2build2) ...
Selecting previously unselected package libexif-dev:amd64.
Preparing to unpack .../libexif-dev_0.6.24-1build1_amd64.deb ...
Unpacking libexif-dev:amd64 (0.6.24-1build1) ...
Selecting previously unselected package libexif-doc.
Preparing to unpack .../libexif-doc_0.6.24-1build1_all.deb ...
Unpacking libexif-doc (0.6.24-1build1) ...
Selecting previously unselected package libexif12:amd64.
Preparing to unpack .../libexif12_0.6.24-1build1_amd64.deb ...
Unpacking libexif12:amd64 (0.6.24-1build1) ...
Selecting previously unselected package libexpat1-dev:amd64.
Preparing to unpack .../libexpat1-dev_2.4.7-1ubuntu0.2_amd64.deb ...
Unpacking libexpat1-dev:amd64 (2.4.7-1ubuntu0.2) ...
Selecting previously unselected package libffi-dev:amd64.
Preparing to unpack .../libffi-dev_3.4.2-4_amd64.deb ...
Unpacking libffi-dev:amd64 (3.4.2-4) ...
Selecting previously unselected package libfftw3-bin.
Preparing to unpack .../libfftw3-bin_3.3.8-2ubuntu8_amd64.deb ...
Unpacking libfftw3-bin (3.3.8-2ubuntu8) ...
Selecting previously unselected package libfftw3-dev:amd64.
Preparing to unpack .../libfftw3-dev_3.3.8-2ubuntu8_amd64.deb ...
Unpacking libfftw3-dev:amd64 (3.3.8-2ubuntu8) ...
Selecting previously unselected package libfftw3-double3:amd64.
Preparing to unpack .../libfftw3-double3_3.3.8-2ubuntu8_amd64.deb ...
Unpacking libfftw3-double3:amd64 (3.3.8-2ubuntu8) ...
Selecting previously unselected package libfftw3-long3:amd64.
Preparing to unpack .../libfftw3-long3_3.3.8-2ubuntu8_amd64.deb ...
Unpacking libfftw3-long3:amd64 (3.3.8-2ubuntu8) ...
Selecting previously unselected package libfftw3-quad3:amd64.
Preparing to unpack .../libfftw3-quad3_3.3.8-2ubuntu8_amd64.deb ...
Unpacking libfftw3-quad3:amd64 (3.3.8-2ubuntu8) ...
Selecting previously unselected package libfftw3-single3:amd64.
Preparing to unpack .../libfftw3-single3_3.3.8-2ubuntu8_amd64.deb ...
Unpacking libfftw3-single3:amd64 (3.3.8-2ubuntu8) ...
Selecting previously unselected package libfontconfig-dev:amd64.
Preparing to unpack .../libfontconfig-dev_2.13.1-4.2ubuntu5_amd64.deb ...
Unpacking libfontconfig-dev:amd64 (2.13.1-4.2ubuntu5) ...
Selecting previously unselected package libfontconfig1-dev:amd64.
Preparing to unpack .../libfontconfig1-dev_2.13.1-4.2ubuntu5_amd64.deb ...
Unpacking libfontconfig1-dev:amd64 (2.13.1-4.2ubuntu5) ...
Selecting previously unselected package libfribidi-dev:amd64.
Preparing to unpack .../libfribidi-dev_1.0.8-2ubuntu3.1_amd64.deb ...
Unpacking libfribidi-dev:amd64 (1.0.8-2ubuntu3.1) ...
Selecting previously unselected package libfuse3-3:amd64.
Preparing to unpack .../libfuse3-3_3.10.5-1build1_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.10.5-1build1) ...
Selecting previously unselected package libgail-common:amd64.
Preparing to unpack .../libgail-common_2.24.33-2ubuntu2_amd64.deb ...
Unpacking libgail-common:amd64 (2.24.33-2ubuntu2) ...
Selecting previously unselected package libgail18:amd64.
Preparing to unpack .../libgail18_2.24.33-2ubuntu2_amd64.deb ...
Unpacking libgail18:amd64 (2.24.33-2ubuntu2) ...
Selecting previously unselected package libgdk-pixbuf-2.0-dev:amd64.
Preparing to unpack .../libgdk-pixbuf-2.0-dev_2.42.8dfsg-1ubuntu0.2_amd64.deb ...
Unpacking libgdk-pixbuf-2.0-dev:amd64 (2.42.8+dfsg-1ubuntu0.2) ...
Selecting previously unselected package libgdk-pixbuf2.0-bin.
Preparing to unpack .../libgdk-pixbuf2.0-bin_2.42.8dfsg-1ubuntu0.2_amd64.deb ...
Unpacking libgdk-pixbuf2.0-bin (2.42.8+dfsg-1ubuntu0.2) ...
Selecting previously unselected package libgif-dev.
Preparing to unpack .../libgif-dev_5.1.9-2build2_amd64.deb ...
Unpacking libgif-dev (5.1.9-2build2) ...
Selecting previously unselected package libglib2.0-dev-bin.
Preparing to unpack .../libglib2.0-dev-bin_2.72.4-0ubuntu2.2_amd64.deb ...
Unpacking libglib2.0-dev-bin (2.72.4-0ubuntu2.2) ...
Selecting previously unselected package libglib2.0-dev:amd64.
Preparing to unpack .../libglib2.0-dev_2.72.4-0ubuntu2.2_amd64.deb ...
Unpacking libglib2.0-dev:amd64 (2.72.4-0ubuntu2.2) ...
Selecting previously unselected package libgraphite2-dev:amd64.
Preparing to unpack .../libgraphite2-dev_1.3.14-1build2_amd64.deb ...
Unpacking libgraphite2-dev:amd64 (1.3.14-1build2) ...
Selecting previously unselected package libgs9-common.
Preparing to unpack .../libgs9-common_9.55.0dfsg1-0ubuntu5.5_all.deb ...
Unpacking libgs9-common (9.55.0~dfsg1-0ubuntu5.5) ...
Selecting previously unselected package libgs9:amd64.
Preparing to unpack .../libgs9_9.55.0dfsg1-0ubuntu5.5_amd64.deb ...
Unpacking libgs9:amd64 (9.55.0~dfsg1-0ubuntu5.5) ...
Selecting previously unselected package libgsf-1-114:amd64.
Preparing to unpack .../libgsf-1-114_1.14.47-1build2_amd64.deb ...
Unpacking libgsf-1-114:amd64 (1.14.47-1build2) ...
Selecting previously unselected package libgsf-1-common.
Preparing to unpack .../libgsf-1-common_1.14.47-1build2_all.deb ...
Unpacking libgsf-1-common (1.14.47-1build2) ...
Selecting previously unselected package libgsf-1-dev:amd64.
Preparing to unpack .../libgsf-1-dev_1.14.47-1build2_amd64.deb ...
Unpacking libgsf-1-dev:amd64 (1.14.47-1build2) ...
Selecting previously unselected package libgsl27:amd64.
Preparing to unpack .../libgsl27_2.7.1dfsg-3_amd64.deb ...
Unpacking libgsl27:amd64 (2.7.1+dfsg-3) ...
Selecting previously unselected package libgslcblas0:amd64.
Preparing to unpack .../libgslcblas0_2.7.1dfsg-3_amd64.deb ...
Unpacking libgslcblas0:amd64 (2.7.1+dfsg-3) ...
Selecting previously unselected package libgtk2.0-0:amd64.
Preparing to unpack .../libgtk2.0-0_2.24.33-2ubuntu2_amd64.deb ...
Unpacking libgtk2.0-0:amd64 (2.24.33-2ubuntu2) ...
Selecting previously unselected package libgtk2.0-bin.
Preparing to unpack .../libgtk2.0-bin_2.24.33-2ubuntu2_amd64.deb ...
Unpacking libgtk2.0-bin (2.24.33-2ubuntu2) ...
Selecting previously unselected package libgtk2.0-common.
Preparing to unpack .../libgtk2.0-common_2.24.33-2ubuntu2_all.deb ...
Unpacking libgtk2.0-common (2.24.33-2ubuntu2) ...
Selecting previously unselected package libharfbuzz-dev:amd64.
Preparing to unpack .../libharfbuzz-dev_2.7.4-1ubuntu3.1_amd64.deb ...
Unpacking libharfbuzz-dev:amd64 (2.7.4-1ubuntu3.1) ...
Selecting previously unselected package libharfbuzz-gobject0:amd64.
Preparing to unpack .../libharfbuzz-gobject0_2.7.4-1ubuntu3.1_amd64.deb ...
Unpacking libharfbuzz-gobject0:amd64 (2.7.4-1ubuntu3.1) ...
Selecting previously unselected package libharfbuzz-icu0:amd64.
Preparing to unpack .../libharfbuzz-icu0_2.7.4-1ubuntu3.1_amd64.deb ...
Unpacking libharfbuzz-icu0:amd64 (2.7.4-1ubuntu3.1) ...
Selecting previously unselected package libheif-dev:amd64.
Preparing to unpack .../libheif-dev_1.12.0-2build1_amd64.deb ...
Unpacking libheif-dev:amd64 (1.12.0-2build1) ...
Selecting previously unselected package libheif1:amd64.
Preparing to unpack .../libheif1_1.12.0-2build1_amd64.deb ...
Unpacking libheif1:amd64 (1.12.0-2build1) ...
Selecting previously unselected package libice-dev:amd64.
Preparing to unpack .../libice-dev_23a1.0.10-1build2_amd64.deb ...
Unpacking libice-dev:amd64 (2:1.0.10-1build2) ...
Selecting previously unselected package libicu-dev:amd64.
Preparing to unpack .../libicu-dev_70.1-2_amd64.deb ...
Unpacking libicu-dev:amd64 (70.1-2) ...
Selecting previously unselected package libidn12:amd64.
Preparing to unpack .../libidn12_1.38-4ubuntu1_amd64.deb ...
Unpacking libidn12:amd64 (1.38-4ubuntu1) ...
Selecting previously unselected package libijs-0.35:amd64.
Preparing to unpack .../libijs-0.35_0.35-15build2_amd64.deb ...
Unpacking libijs-0.35:amd64 (0.35-15build2) ...
Selecting previously unselected package libilmbase-dev:amd64.
Preparing to unpack .../libilmbase-dev_2.5.7-2_amd64.deb ...
Unpacking libilmbase-dev:amd64 (2.5.7-2) ...
Selecting previously unselected package libilmbase25:amd64.
Preparing to unpack .../libilmbase25_2.5.7-2_amd64.deb ...
Unpacking libilmbase25:amd64 (2.5.7-2) ...
Selecting previously unselected package libimagequant-dev:amd64.
Preparing to unpack .../libimagequant-dev_2.17.0-1_amd64.deb ...
Unpacking libimagequant-dev:amd64 (2.17.0-1) ...
Selecting previously unselected package libimagequant0:amd64.
Preparing to unpack .../libimagequant0_2.17.0-1_amd64.deb ...
Unpacking libimagequant0:amd64 (2.17.0-1) ...
Selecting previously unselected package libjbig-dev:amd64.
Preparing to unpack .../libjbig-dev_2.1-3.1ubuntu0.22.04.1_amd64.deb ...
Unpacking libjbig-dev:amd64 (2.1-3.1ubuntu0.22.04.1) ...
Selecting previously unselected package libjbig2dec0:amd64.
Preparing to unpack .../libjbig2dec0_0.19-3build2_amd64.deb ...
Unpacking libjbig2dec0:amd64 (0.19-3build2) ...
Selecting previously unselected package libjxr-tools.
Preparing to unpack .../libjxr-tools_1.2git20170615.f752187-5_amd64.deb ...
Unpacking libjxr-tools (1.2~git20170615.f752187-5) ...
Selecting previously unselected package libjxr0:amd64.
Preparing to unpack .../libjxr0_1.2git20170615.f752187-5_amd64.deb ...
Unpacking libjxr0:amd64 (1.2~git20170615.f752187-5) ...
Selecting previously unselected package liblcms2-dev:amd64.
Preparing to unpack .../liblcms2-dev_2.12rc1-2build2_amd64.deb ...
Unpacking liblcms2-dev:amd64 (2.12~rc1-2build2) ...
Selecting previously unselected package liblqr-1-0-dev:amd64.
Preparing to unpack .../liblqr-1-0-dev_0.4.2-2.1_amd64.deb ...
Unpacking liblqr-1-0-dev:amd64 (0.4.2-2.1) ...
Selecting previously unselected package liblqr-1-0:amd64.
Preparing to unpack .../liblqr-1-0_0.4.2-2.1_amd64.deb ...
Unpacking liblqr-1-0:amd64 (0.4.2-2.1) ...
Selecting previously unselected package libltdl-dev:amd64.
Preparing to unpack .../libltdl-dev_2.4.6-15build2_amd64.deb ...
Unpacking libltdl-dev:amd64 (2.4.6-15build2) ...
Selecting previously unselected package liblzma-dev:amd64.
Preparing to unpack .../liblzma-dev_5.2.5-2ubuntu1_amd64.deb ...
Unpacking liblzma-dev:amd64 (5.2.5-2ubuntu1) ...
Selecting previously unselected package liblzo2-2:amd64.
Preparing to unpack .../liblzo2-2_2.10-2build3_amd64.deb ...
Unpacking liblzo2-2:amd64 (2.10-2build3) ...
Selecting previously unselected package libmagic-mgc.
Preparing to unpack .../libmagic-mgc_13a5.41-3ubuntu0.1_amd64.deb ...
Unpacking libmagic-mgc (1:5.41-3ubuntu0.1) ...
Selecting previously unselected package libmagic1:amd64.
Preparing to unpack .../libmagic1_13a5.41-3ubuntu0.1_amd64.deb ...
Unpacking libmagic1:amd64 (1:5.41-3ubuntu0.1) ...
Selecting previously unselected package libmagickcore-6-arch-config:amd64.
Preparing to unpack .../libmagickcore-6-arch-config_83a6.9.11.60dfsg-1.3ubuntu0.22.04.3_amd64.deb ...
Unpacking libmagickcore-6-arch-config:amd64 (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3) ...
Selecting previously unselected package libmagickcore-6-headers.
Preparing to unpack .../libmagickcore-6-headers_83a6.9.11.60dfsg-1.3ubuntu0.22.04.3_all.deb ...
Unpacking libmagickcore-6-headers (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3) ...
Selecting previously unselected package libmagickcore-6.q16-6-extra:amd64.
Preparing to unpack .../libmagickcore-6.q16-6-extra_83a6.9.11.60dfsg-1.3ubuntu0.22.04.3_amd64.deb ...
Unpacking libmagickcore-6.q16-6-extra:amd64 (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3) ...
Selecting previously unselected package libmagickcore-6.q16-6:amd64.
Preparing to unpack .../libmagickcore-6.q16-6_83a6.9.11.60dfsg-1.3ubuntu0.22.04.3_amd64.deb ...
Unpacking libmagickcore-6.q16-6:amd64 (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3) ...
Selecting previously unselected package libmagickcore-6.q16-dev:amd64.
Preparing to unpack .../libmagickcore-6.q16-dev_83a6.9.11.60dfsg-1.3ubuntu0.22.04.3_amd64.deb ...
Unpacking libmagickcore-6.q16-dev:amd64 (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3) ...
Selecting previously unselected package libmagickcore-dev.
Preparing to unpack .../libmagickcore-dev_83a6.9.11.60dfsg-1.3ubuntu0.22.04.3_all.deb ...
Unpacking libmagickcore-dev (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3) ...
Selecting previously unselected package libmagickwand-6-headers.
Preparing to unpack .../libmagickwand-6-headers_83a6.9.11.60dfsg-1.3ubuntu0.22.04.3_all.deb ...
Unpacking libmagickwand-6-headers (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3) ...
Selecting previously unselected package libmagickwand-6.q16-6:amd64.
Preparing to unpack .../libmagickwand-6.q16-6_83a6.9.11.60dfsg-1.3ubuntu0.22.04.3_amd64.deb ...
Unpacking libmagickwand-6.q16-6:amd64 (8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3) ...
Selecting previously unselected package libmagickwand-6.q16-dev:amd64.

In [2]:
import os, glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

DATASET_FOLDER = "/kaggle/input/UBC-OCEAN/"
IMAGES_FOLDER = "./test_tiles"
BAG_SIZE = 6
MAX_SAMPLE_PER_IMAGE = 50 #BAG_SIZE*5
INPUT_SIZE = 512
TILE_SIZE = 1024
BATCH_SIZE = 2
NUM_WORKERS = 2
os.environ['VIPS_CONCURRENCY'] = '4'
os.environ['VIPS_DISC_THRESHOLD'] = '15gb'

## Data for inference

**Note, we canot extract all tiles from all imges because of unsufficient space/storage**

This needs porting several code (classes) form the training notebook:

- extracting the tiles from whole image
- validation argmention, mainly color mean & STD

In [3]:
df_train = pd.read_csv(os.path.join(DATASET_FOLDER, "train.csv"))
LABELS = ['CC', 'EC', 'HGSC', 'LGSC','MC','Stroma','Necrosis']
print(f"{LABELS=}")

LABELS=['CC', 'EC', 'HGSC', 'LGSC', 'MC', 'Stroma', 'Necrosis']

In [4]:
df_train.head()

   image_id label  image_width  image_height  is_tma
0         4  HGSC        23785         20008   False
1        66  LGSC        48871         48195   False
2        91  HGSC         3388          3388    True
3       281  LGSC        42309         15545   False
4       286    EC        37204         30020   False

In [5]:
df_train.groupby('image_id').get_group(4)['is_tma'].item()

False

In [6]:
TH_TMA_FILE_SIZE   = 1.5
!du -s -m /kaggle/input/UBC-OCEAN/test_images/* > amount.csv
df_size = pd.read_csv("amount.csv", delimiter='\t', header=None).rename(columns={0:"size_mb", 1:"file"})
df_size["image_id"] = df_size["file"].apply(lambda x: int(os.path.basename(x).split(".")[0] ) )
df_size["size_mb_log10"] = np.log10(df_size["size_mb"].values)
df_size["is_tma"] = df_size["size_mb_log10"] < TH_TMA_FILE_SIZE
# df_size.set_index('image_id',inplace = True)
df_size

,size_mb,file,image_id,size_mb_log10,is_tma
0,621,/kaggle/input/UBC-OCEAN/test_images/41.png,41,2.793092,False

In [7]:
import os
import pyvips
import numpy as np
import random
from PIL import Image
import gc

def drop_bg(tile, area_thresh = 0.6, white_thresh = 220):
    drop_black = False
    drop_white = False
    mask_bg = np.sum(tile, axis=2) == 0
    if np.sum(mask_bg) >= (np.prod(mask_bg.shape) * area_thresh): # too much black
        drop_black = True
    tile[mask_bg, :] = 255
    mask_bg = np.mean(tile, axis=2) > white_thresh
    if np.sum(mask_bg) >= (np.prod(mask_bg.shape) * area_thresh):# too much white
        drop_white = True
#     if drop_black:
#         print('too many blacks')
#     if drop_white:
#         print('too many whites')
    return drop_black or drop_white

def evaluate_tumor_quality(model, dataloader):
    model.eval()
    model = model.to('cuda')
    preds = []
    for batch in dataloader:
        pred = model(batch.cuda())
        preds.append(pred.detach().cpu())
        
    
    preds = torch.cat(preds)
#     print(preds.shape)
    preds = torch.softmax(preds, axis = 1)
    labels = torch.argmax(preds, axis = 1).numpy()
    proba = torch.max(preds, axis=1).values.numpy()
#     print(labels, proba)
    has_tumor = [l in range(5) for l, p in zip(labels, proba)]
#     print(list(zip(labels, proba, has_tumor)))
    model = model.to('cpu')
    return has_tumor

def extract_image_tiles(
    img_wsi,
    tile_size = 1024,
    resize_shape = None,
    max_sample=None,
    check_drop_bg  =True,
    patch_classifier_model = None
):
    im = img_wsi# pyvips.Image.new_from_file(p_img)
    w = h = tile_size
    # https://stackoverflow.com/a/47581978/4521646
    idxs = [(y, y + h, x, x + w) for y in range(0, im.height, h) for x in range(0, im.width, w)]
    print('total patches', len(idxs))
    
    np.random.seed(42)
    if max_sample:
        np.random.shuffle(idxs)
        idxs = idxs[:max_sample]
    
    dataset_bg_det = BG_Det_Dataset(im, idxs, tile_size = tile_size)
    dataloader_bg_det = DataLoader(
            dataset_bg_det, batch_size=4, num_workers=0, shuffle=False,
        )
    del im
    for _ in range(5):
        gc.collect()
    bool_indices = []
    tiles = []
    for tiles_batch, batch_bool in tqdm(dataloader_bg_det):
        bool_indices+=list(batch_bool)
        tiles.append(tiles_batch)
    tiles = np.concatenate(tiles)
    tile_list_no_bg = np.array(tiles)[~np.array(bool_indices)]
    print('patches after filtering background', len(tile_list_no_bg))
    
    if len(tile_list_no_bg) == 0:
        return tiles[:BAG_SIZE*4]

    dataset = PatchesDataset(
        [Image.fromarray(tile) for tile in tile_list_no_bg], 
        patch_classifier_model['preprocess']
    )
    dataloader = DataLoader(
            dataset, batch_size=BATCH_SIZE, num_workers=NUM_WORKERS, shuffle=False,
        )
    has_tumor = evaluate_tumor_quality(patch_classifier_model['model'], dataloader)
    
    tile_list_no_bg_pc = np.array(tile_list_no_bg)[has_tumor]
    print('patches after filtering background and patch classification', len(tile_list_no_bg_pc))

    if len(tile_list_no_bg_pc) < BAG_SIZE:
        print('patches got removed due to bg removal and patch classifier, adding random bags')
#         tile_list_no_bg_pc = list(tile_list_no_bg_pc)
#         tile_list_no_bg_pc += list(tile_list_no_bg[:BAG_SIZE*4])
#         print(np.array(tile_list_no_bg_pc).shape)
        
    
    del dataset, dataloader
    for _ in range(5):
        gc.collect()
#     for img in tile_list_no_bg_pc[:10]:
#         plt.imshow(img)
#         plt.show()
    return tile_list_no_bg_pc

In [8]:
from torchvision import transforms as T

img_color_mean = [0.8721593659261734, 0.7799686061900686, 0.8644588534918227]
img_color_std = [0.08258995918115268, 0.10991684444009092, 0.06839816226731532]

VALID_TRANSFORM = T.Compose([
    T.Resize((INPUT_SIZE,INPUT_SIZE)),
    T.ToTensor(),
    #T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    T.Normalize(img_color_mean, img_color_std),  # custom
])

In [9]:
import torch
from PIL import Image
from torch.utils.data import Dataset

class TilesDataset(Dataset):

    def __init__(
        self,
        tiles,
        bag_size,
        transforms
    ):
        self.transforms = transforms
        self.imgs = tiles
        self.available_bags = len(self.imgs)//bag_size if len(self.imgs)//bag_size>0 else 1
        self.bag_size = bag_size
        self.imgs_bags = [self.imgs[i*bag_size:i*bag_size+bag_size] for i in range(self.available_bags) ]

    def __getitem__(self, idx: int) -> tuple:
        bag = self.imgs_bags[idx]
        # augmentation
        if self.transforms:
            bag =[self.transforms(Image.fromarray(item))  for item in bag]
        #print(f"img dim: {img.shape}")
#         print(bag)
        return torch.stack(bag)#, torch.tensor(labels).to(int)


    def __len__(self) -> int:
        return self.available_bags
    
class PatchesDataset(Dataset):
    def __init__(
        self,
        tiles,
        transforms
    ):
        self.transforms = transforms
        self.tiles = tiles

    def __getitem__(self, idx: int) -> tuple:
        tile = self.tiles[idx]
        tile = self.transforms(tile)
        return tile

    def __len__(self) -> int:
        return len(self.tiles)
    
class BG_Det_Dataset(Dataset):
    def __init__(
        self,
        im,
        idxs,
        tile_size
    ):
        self.im = im
        self.idxs = idxs
        self.tile_size = tile_size

    def __getitem__(self, idx: int) -> tuple:
        y, y_, x, x_ = self.idxs[idx]
        # make tile
        w = h = self.tile_size
        tile = self.im.crop(x, y, min(w, self.im.width - x), min(h, self.im.height - y)).numpy()[..., :3]
        if tile.shape[:2] != (h, w):
            tile_ = tile
            tile_size = (h, w) if tile.ndim == 2 else (h, w, tile.shape[2])
            tile = np.zeros(tile_size, dtype=tile.dtype)
            tile[:tile_.shape[0], :tile_.shape[1], ...] = tile_
        drop_bool = drop_bg(tile.copy())
#         if drop_bool == True:
#             tile = []
        return tile, drop_bool
    def __len__(self) -> int:
        return len(self.idxs)

## CNN Model

We start with some stanrd CNN models taken from torch vision.

In [10]:
import timm
import torch
import torchvision
import pytorch_lightning as pl
from torch import nn
from torch.nn import functional as F


enc= timm.create_model(
    'tiny_vit_21m_512.dist_in22k_ft_in1k', pretrained=False, num_classes=7)
class Model(nn.Module):
    def __init__(self,enc):
        super().__init__()
        self.enc = enc
    def forward(self, x):
        return self.enc(x)
model_pc = Model(enc)
model_data = torch.load('/kaggle/input/2023-12-09-17-07-51/tiny_vit_21m_512.dist_in22k_ft_in1k/version_0/checkpoints/epoch=4-step=9925.ckpt')
model_pc.load_state_dict(model_data['state_dict'])

patch_classifier_model = {
    'model': model_pc,
    'preprocess': VALID_TRANSFORM
}

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [11]:
import gc
gc.collect()

47

In [12]:
import torch
import torch.nn as nn

class AdaptiveConcatPool2d(torch.nn.Module):
    "Layer that concats `AdaptiveAvgPool2d` and `AdaptiveMaxPool2d`"
    def __init__(self, size=None):
        super().__init__()
        self.size = size or 1
        self.ap = torch.nn.AdaptiveAvgPool2d(self.size)
        self.mp = torch.nn.AdaptiveMaxPool2d(self.size)
    def forward(self, x): return torch.cat([self.mp(x), self.ap(x)], 1)


class Model_BOW(nn.Module):
    def __init__(self, enc, feature_dim,
                 num_class = 5):
        super().__init__()
    #         self.conv_bag = torch.nn.Conv2d(in_channels=12*3,out_channels=3,kernel_size=3,padding=1)
    #         self.net = net
    #         self.arch = net.pretrained_cfg.get('architecture')
        self.num_classes = num_class
        self.enc = enc
        self.feature_dim = feature_dim
        self.head = nn.Sequential(
            AdaptiveConcatPool2d(),
            torch.nn.Flatten(),
            nn.Linear(2*feature_dim,512),
            torch.nn.ReLU(),
            #torch.nn.Mish(),
            torch.nn.LayerNorm(512),
            nn.Linear(512,256),
            torch.nn.ReLU(),
            torch.nn.Mish(),
            torch.nn.LayerNorm(256),
            #torch.nn.Dropout(0.5),
            torch.nn.Linear(256,self.num_classes)
        )


        
    def forward(self, x, x_large):
        batch,bag,c,h,w = x.shape

        x = x.view(batch*bag, c,h,w)
        #x: bs*N x C x 4 x 4
        x = self.enc(x)
        _,c_out,h_out,w_out = x.shape
        #concatenate the output for tiles into a single map
        x = x.view(batch,bag,c_out,h_out,w_out)
        #x: bsxN x C x 4 x 4
        #print(x.shape)
        x_l = self.enc(x_large)
        #print(x_l.shape)
        x_l = x_l.unsqueeze(1)
        x=torch.cat([x,x_l], axis=1)

        #x_l = x_l.repeat(1,bag,1,1,1)
        #x = x+x_l # add?

        x = x.permute(0,2,1,3,4).contiguous() # bs,C,N,H,W
        #print(x.shape)
        x = x.view(batch,c_out,h_out*(bag+1),w_out)
        #print(x.shape)
        x = self.head(x)

        #x: bs x n
        return x

net= timm.create_model(
    'maxvit_tiny_tf_512', pretrained=False, num_classes=5)
net = nn.Sequential(*list(net.children())[:-1])
model_bow=Model_BOW(enc=net, feature_dim=512)
model_data = torch.load('/kaggle/input/2023-12-14-20-32-38/fold_0/maxvit_tiny_tf_512/version_0/checkpoints/epoch=99-step=3400.ckpt')
model_bow.load_state_dict(model_data['state_dict'])

## Test data & submission

lest load sample submission and add append images we can predict

In [13]:
df_test = pd.read_csv(os.path.join(DATASET_FOLDER, "test.csv"))
# default label
df_test['label'] = ['HGSC'] * len(df_test)
# labels = list(df_train["label"].unique())
print(f"Dataset/test size: {len(df_test)}")
display(df_test.head())

Dataset/test size: 1

   image_id  image_width  image_height label
0        41        28469         16987  HGSC

In [14]:
!cat /kaggle/input/UBC-OCEAN/sample_submission.csv

image_id,label
41,HGSC

## Inference

In [15]:
def infer_single_image(model, patch_classifier_model, row, train):
    row = dict(row)
    # prepare data - cut and load tiles
    if train:
        split = 'train'
    else:
        split = 'test'
    path = os.path.join(DATASET_FOLDER, "{}_images".format(split), f"{str(row['image_id'])}.png")
    img_wsi = pyvips.Image.new_from_file(path)

    tiles = extract_image_tiles(
        img_wsi,
        tile_size=TILE_SIZE, 
        max_sample=MAX_SAMPLE_PER_IMAGE,
        patch_classifier_model = patch_classifier_model
    )
#     print(tiles[0].shape)

    del img_wsi
    for _ in range(5):
        gc.collect()
    
    if len(tiles)==0:
        row['label'] = 'Other'
    else:
        
        img_global = Image.open(os.path.join(
            '/kaggle/input/UBC-OCEAN/{}_thumbnails'.format(split),
            '{}_thumbnail.png'.format(row['image_id'])
        ))
    #     img_global = np.array(img_global)
        img_global = data_transforms_valid(image = np.array(img_global))['image']
        img_global = img_global.unsqueeze(0)


        dataset = TilesDataset(tiles, bag_size=BAG_SIZE,transforms=VALID_TRANSFORM)
        dataloader = DataLoader(
                dataset, batch_size=BATCH_SIZE, num_workers=NUM_WORKERS, shuffle=False,
        #                            multiprocessing_context=get_context('loky')
            )
        print('bags', len(dataset))
        # iterate over images and collect predictions
        preds = []
        model = model.to('cuda')
        for imgs in dataloader:
            #print(f"{imgs.shape}")
            img_global_batch = torch.cat([img_global.clone()]*len(imgs))
            img_global_batch = img_global_batch.cuda()
            with torch.no_grad():
                pred = model(imgs.cuda(), img_global_batch)
            preds.append(pred.detach().cpu())
        model = model.to('cpu')
        # decide label
        preds = torch.cat(preds)
        print(preds.shape)
        preds = torch.mean(preds, axis=0)
        preds = torch.softmax(preds.view(-1), axis=0)
        print(preds)
        lb = np.argmax(preds)
        row['label'] = LABELS[lb]

        del dataset, dataloader
        for _ in range(5):
            gc.collect()

    return row

In [16]:
def infer_single_image_tma(model, row, train):
    
    model = model.to('cuda')
    model.eval()
    row = dict(row)
    if train:
        split = 'train'
    else: 
        split = 'test'
    path = os.path.join('/kaggle/input/UBC-OCEAN/{}_images/{}.png'.format(split, row['image_id']))
    img = Image.open(path)
    img = np.array(img)
    pred = np.zeros((1,7))
    for tx in rotate_tx:
        img_tx = tx(image = img)['image']   
        img_tx = data_transforms_valid(image = img_tx)['image']
        img_tx = img_tx.unsqueeze(0)
        #print(f"{imgs.shape}")
        with torch.no_grad():
#             print(model(img_tx.cuda()).detach().cpu().numpy())
            pred += model(img_tx.cuda()).detach().cpu().numpy()
    # decide label
    model = model.to('cpu')
    lb = np.argmax(pred)
    row['label'] = LABELS[lb]
    return row

In [17]:
import albumentations as A
from albumentations.pytorch import ToTensorV2

item = (2048, 512)
data_transforms_valid = A.Compose([
            A.PadIfNeeded(item[0], item[0]),
            A.CenterCrop(item[0], item[0]),
            A.Resize(item[1], item[1]),
            A.Normalize(
                mean = img_color_mean, #[0.485, 0.456, 0.406], 
                std = img_color_std, #[0.229, 0.224, 0.225], 
                max_pixel_value=255.0, 
                p=1.0
            ),
            ToTensorV2()], p=1.)

tx90 = A.Compose(
    [
        A.Rotate(limit=(90,90),always_apply=True, p=1.0),
#         A.Resize(4,4)
    ], p=1.0)
tx180 = A.Compose(
    [
        A.Rotate(limit=(90,90),always_apply=True, p=1.0),
#         A.Resize(4,4)
    ]*2, p=1.0)
tx270 = A.Compose(
    [
        A.Rotate(limit=(90,90),always_apply=True, p=1.0),
#         A.Resize(4,4)
    ]*3, p=1.0)
rotate_tx = [tx90, tx180, tx270]

In [18]:
import shutil
from torch.utils.data import DataLoader
from joblib.externals.loky.backend.context import get_context
from tqdm.auto import tqdm 
import time

model_bow.eval()
TRAIN = False

submission = []
if TRAIN:
    df_select = df_train.copy()
else:
    df_select = df_test.copy()
    
# df_select = df_select[50:100]    

for i, row in tqdm(df_select.iterrows(), total = len(df_select)):
    print(row.to_list())
    if TRAIN:
        is_tma = df_select.groupby('image_id').get_group(row['image_id'])['is_tma'].item()
    else:
        is_tma = df_size.groupby('image_id').get_group(row['image_id'])['is_tma'].item()
    if is_tma:
        row = infer_single_image(model_bow, patch_classifier_model, row, TRAIN)

        row = infer_single_image_tma(model_pc, row, TRAIN)
        if row['label'] in ['Stroma', 'Necrosis']:
            row['label'] = 'Other'
        submission.append(dict(row))
    else:
        start = time.time()
        row = infer_single_image(model_bow, patch_classifier_model, row, TRAIN)
#         print(row)
        submission.append(dict(row))
        print(time.time()-start)
    print(row)
df_sub = pd.DataFrame(submission)

  0%|          | 0/1 [00:00<?, ?it/s]

[41, 28469, 16987, 'HGSC']
total patches 476

  0%|          | 0/13 [00:00<?, ?it/s]

patches after filtering background 22
patches after filtering background and patch classification 0
patches got removed due to bg removal and patch classifier, adding random bags
30.581491947174072
{'image_id': 41, 'image_width': 28469, 'image_height': 16987, 'label': 'Other'}

In [19]:
# from sklearn import metrics

# print(metrics.balanced_accuracy_score(df_train[~df_train['is_tma']].label.values, df_sub[~df_train['is_tma']].label.values))

# print(metrics.confusion_matrix(df_train[~df_train['is_tma']].label.values, df_sub[~df_train['is_tma']].label.values))

## Finalize - export submission

In [20]:
display(df_sub.head())
df_sub[["image_id", "label"]].to_csv("submission.csv", index=False)

! head submission.csv

   image_id  image_width  image_height  label
0        41        28469         16987  Other

image_id,label
41,Other